set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256color*:Tc"
set -s escape-time 10
set -g set-clipboard on

set -g mouse on
set -g history-limit 100000
set -g renumber-windows on

setw -g mode-keys vi
set -g detach-on-destroy off
